site_name: Vectorly API docs
theme_dir: cinder
pages:
- Home: index.md
- Compressing Videos: compressing.md
- Playing Videos: playing.md
- Technology: technology.md


copyright: Copyright &copy; 2019 Vectorly