site_name: dot Learn Integration guide
theme_dir: cinder
pages:
- Home: index.md
- Compressing Videos: compressing.md
- Playing Videos: playing.md
- Technology: technology.md


copyright: Copyright &copy; 2018 dot Learn